# Generated by Django 2.1.1 on 2018-11-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No Division Name', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No League Name', max_length=100, unique=True)),
                ('current_week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('matchup_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_points', models.IntegerField(default=0)),
                ('away_team_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('NA', 'NA')], default='NA', max_length=2)),
                ('starter', models.BooleanField()),
                ('current_points', models.IntegerField(default=0)),
                ('NFL_team', models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Buffalo Bills', 'Buffalo Bills'), ('Carolina Panthers', 'Carolina Panthers'), ('Chicago Bears', 'Chicago Bears'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='No Team Name', max_length=100, unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('current_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_number', models.IntegerField(primary_key=True, serialize=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFDB.League')),
            ],
        ),
        migrations.CreateModel(
            name='Playerprojection',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FFDB.Player')),
                ('pass_yards', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('touchdowns', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tradingblock',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FFDB.Team')),
                ('team_needs', models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('NA', 'NA')], default='NA', max_length=2)),
                ('team_availables', models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('NA', 'NA')], default='NA', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FFDB.Division'),
        ),
        migrations.AddField(
            model_name='player',
            name='league_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='FFDB.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='FFDB.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='FFDB.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFDB.Week'),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFDB.League'),
        ),
        migrations.AddField(
            model_name='tradingblock',
            name='interested_in',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='FFDB.Player'),
        ),
    ]
