# Generated by Django 2.1.1 on 2018-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='concluded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='NFL_team',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Buffalo Bills', 'Buffalo Bills'), ('Carolina Panthers', 'Carolina Panthers'), ('Chicago Bears', 'Chicago Bears'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Denver Broncos', 'Denver Broncos'), ('Detroit Lions', 'Detroit Lions'), ('Green Bay Packers', 'Green Bay Packers'), ('Houston Texans', 'Houston Texans'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Kansas City', 'Kansas City'), ('Miami Dolphins', 'Miami Dolphins'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New England Patriots', 'New England Patriots'), ('New Orleans Saints', 'New Orleans Saints'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Oakland Raiders', 'Oakland Raiders'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('Pittsburgh Steelers', 'Pittsburgh Steelers'), ('St. Louis Rams', 'St. Louis Rams'), ('San Diego Chargers', 'San Diego Chargers'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Seattle Seahawks', 'Seattle Seahawks'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Tennessee Titans', 'Tennessee Titans'), ('Washington Redskins', 'Washington Redskins')], default=None, max_length=100),
        ),
    ]
