# Generated by Django 2.1.1 on 2018-11-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFDB', '0003_our_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_user',
            name='owns_team',
            field=models.BooleanField(default=False),
        ),
    ]
